baseurl: https://flopsis.com/
languageCode: en-us
title: flopsis
caches:
  assets:
    dir: :resourceDir/_gen
    maxage: -1
  getcsv:
    dir: :cacheDir/:project
    maxage: -1
  getjson:
    dir: :cacheDir/:project
    maxage: -1
  getresource:
    dir: :cacheDir/:project
    maxage: -1
  images:
    dir: :cacheDir/images
    maxage: -1
  misc:
    dir: :cacheDir/:project
    maxage: -1
  modules:
    dir: :cacheDir/modules
    maxage: -1
params: 
  homeInfoParams:
    Title: "Reinis ZiediÅ†Å¡ \n Economics and Game Development"
    Content: "Welcome ðŸš² \n\n
    checkout my projects below"
    socialIcons: 
    - name: github
      url: "https://github.com/Ziedins"
