baseurl: https://flopsis.com/
languageCode: en-us
title: flopsis
theme: PaperMod
caches:
  assets:
    dir: :resourceDir/_gen
    maxage: -1
  getcsv:
    dir: :cacheDir/:project
    maxage: -1
  getjson:
    dir: :cacheDir/:project
    maxage: -1
  getresource:
    dir: :cacheDir/:project
    maxage: -1
  images:
    dir: :cacheDir/images
    maxage: -1
  misc:
    dir: :cacheDir/:project
    maxage: -1
  modules:
    dir: :cacheDir/modules
    maxage: -1
params: 
  homeInfoParams:
    Title: "Reinis ZiediÅ†Å¡"
    Email: ziedinslu@gmail.com
    Content: "Hey there, welcome to my website : \n\n

    Economics ðŸ“ˆ  \n\n
    Development ðŸ’» \n\n
    Cycling ðŸš² \n\n
    Checkout my content below"
  socialIcons: 
    - name: github
      url: "https://github.com/Ziedins"
